# Generated by Django 5.0 on 2024-01-01 21:35

import image_speech.filepaths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_speech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=image_speech.filepaths.audio_path),
        ),
    ]
